/*
 * service/service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Serviceserviceproto);
  }
}(this, function(expect, Serviceserviceproto) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ParcelApiAuditParcel', function() {
      beforeEach(function() {
        instance = new Serviceserviceproto.ParcelApiAuditParcel();
      });

      it('should create an instance of ParcelApiAuditParcel', function() {
        // TODO: update the code to test ParcelApiAuditParcel
        expect(instance).to.be.a(Serviceserviceproto.ParcelApiAuditParcel);
      });

      it('should have the property changer (base name: "changer")', function() {
        // TODO: update the code to test the property changer
        expect(instance).to.have.property('changer');
        // expect(instance.changer).to.be(expectedValueLiteral);
      });

      it('should have the property time (base name: "time")', function() {
        // TODO: update the code to test the property time
        expect(instance).to.have.property('time');
        // expect(instance.time).to.be(expectedValueLiteral);
      });

      it('should have the property parcel (base name: "parcel")', function() {
        // TODO: update the code to test the property parcel
        expect(instance).to.have.property('parcel');
        // expect(instance.parcel).to.be(expectedValueLiteral);
      });

    });
  });

}));
