/*
 * service/service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AuthApiAuthRequest', 'model/AuthApiAuthResponce', 'model/AuthApiCheckResponce', 'model/AuthApiCreateRequest', 'model/AuthApiCreateResponce', 'model/AuthApiGetRolesResponce', 'model/AuthApiGetUsersResponce', 'model/AuthApiRefreshRequest', 'model/AuthApiUpdateUserRequest', 'model/AuthApiUpdateUserResponce', 'model/GetRolesResponceRole', 'model/GetUsersResponceUser', 'model/ProtobufAny', 'model/RpcStatus', 'api/AuthServiceApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AuthApiAuthRequest'), require('./model/AuthApiAuthResponce'), require('./model/AuthApiCheckResponce'), require('./model/AuthApiCreateRequest'), require('./model/AuthApiCreateResponce'), require('./model/AuthApiGetRolesResponce'), require('./model/AuthApiGetUsersResponce'), require('./model/AuthApiRefreshRequest'), require('./model/AuthApiUpdateUserRequest'), require('./model/AuthApiUpdateUserResponce'), require('./model/GetRolesResponceRole'), require('./model/GetUsersResponceUser'), require('./model/ProtobufAny'), require('./model/RpcStatus'), require('./api/AuthServiceApi'));
  }
}(function(ApiClient, AuthApiAuthRequest, AuthApiAuthResponce, AuthApiCheckResponce, AuthApiCreateRequest, AuthApiCreateResponce, AuthApiGetRolesResponce, AuthApiGetUsersResponce, AuthApiRefreshRequest, AuthApiUpdateUserRequest, AuthApiUpdateUserResponce, GetRolesResponceRole, GetUsersResponceUser, ProtobufAny, RpcStatus, AuthServiceApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Serviceserviceproto = require('index'); // See note below*.
   * var xxxSvc = new Serviceserviceproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Serviceserviceproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Serviceserviceproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Serviceserviceproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version version not set
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AuthApiAuthRequest model constructor.
     * @property {module:model/AuthApiAuthRequest}
     */
    AuthApiAuthRequest: AuthApiAuthRequest,
    /**
     * The AuthApiAuthResponce model constructor.
     * @property {module:model/AuthApiAuthResponce}
     */
    AuthApiAuthResponce: AuthApiAuthResponce,
    /**
     * The AuthApiCheckResponce model constructor.
     * @property {module:model/AuthApiCheckResponce}
     */
    AuthApiCheckResponce: AuthApiCheckResponce,
    /**
     * The AuthApiCreateRequest model constructor.
     * @property {module:model/AuthApiCreateRequest}
     */
    AuthApiCreateRequest: AuthApiCreateRequest,
    /**
     * The AuthApiCreateResponce model constructor.
     * @property {module:model/AuthApiCreateResponce}
     */
    AuthApiCreateResponce: AuthApiCreateResponce,
    /**
     * The AuthApiGetRolesResponce model constructor.
     * @property {module:model/AuthApiGetRolesResponce}
     */
    AuthApiGetRolesResponce: AuthApiGetRolesResponce,
    /**
     * The AuthApiGetUsersResponce model constructor.
     * @property {module:model/AuthApiGetUsersResponce}
     */
    AuthApiGetUsersResponce: AuthApiGetUsersResponce,
    /**
     * The AuthApiRefreshRequest model constructor.
     * @property {module:model/AuthApiRefreshRequest}
     */
    AuthApiRefreshRequest: AuthApiRefreshRequest,
    /**
     * The AuthApiUpdateUserRequest model constructor.
     * @property {module:model/AuthApiUpdateUserRequest}
     */
    AuthApiUpdateUserRequest: AuthApiUpdateUserRequest,
    /**
     * The AuthApiUpdateUserResponce model constructor.
     * @property {module:model/AuthApiUpdateUserResponce}
     */
    AuthApiUpdateUserResponce: AuthApiUpdateUserResponce,
    /**
     * The GetRolesResponceRole model constructor.
     * @property {module:model/GetRolesResponceRole}
     */
    GetRolesResponceRole: GetRolesResponceRole,
    /**
     * The GetUsersResponceUser model constructor.
     * @property {module:model/GetUsersResponceUser}
     */
    GetUsersResponceUser: GetUsersResponceUser,
    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny: ProtobufAny,
    /**
     * The RpcStatus model constructor.
     * @property {module:model/RpcStatus}
     */
    RpcStatus: RpcStatus,
    /**
     * The AuthServiceApi service constructor.
     * @property {module:api/AuthServiceApi}
     */
    AuthServiceApi: AuthServiceApi
  };

  return exports;
}));
