/*
 * service/service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Serviceserviceproto) {
      root.Serviceserviceproto = {};
    }
    root.Serviceserviceproto.AuthApiCheckResponce = factory(root.Serviceserviceproto.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AuthApiCheckResponce model module.
   * @module model/AuthApiCheckResponce
   * @version version not set
   */

  /**
   * Constructs a new <code>AuthApiCheckResponce</code>.
   * @alias module:model/AuthApiCheckResponce
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AuthApiCheckResponce</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthApiCheckResponce} obj Optional instance to populate.
   * @return {module:model/AuthApiCheckResponce} The populated <code>AuthApiCheckResponce</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('userRolesIds'))
        obj.userRolesIds = ApiClient.convertToType(data['userRolesIds'], ['String']);
    }
    return obj;
  }

  /**
   * @member {String} userId
   */
  exports.prototype.userId = undefined;

  /**
   * @member {Array.<String>} userRolesIds
   */
  exports.prototype.userRolesIds = undefined;


  return exports;

}));
