/*
 * service/service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ParcelApiParcel'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ParcelApiParcel'));
  } else {
    // Browser globals (root is window)
    if (!root.Serviceserviceproto) {
      root.Serviceserviceproto = {};
    }
    root.Serviceserviceproto.ParcelApiAuditParcel = factory(root.Serviceserviceproto.ApiClient, root.Serviceserviceproto.ParcelApiParcel);
  }
}(this, function(ApiClient, ParcelApiParcel) {
  'use strict';

  /**
   * The ParcelApiAuditParcel model module.
   * @module model/ParcelApiAuditParcel
   * @version version not set
   */

  /**
   * Constructs a new <code>ParcelApiAuditParcel</code>.
   * @alias module:model/ParcelApiAuditParcel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ParcelApiAuditParcel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ParcelApiAuditParcel} obj Optional instance to populate.
   * @return {module:model/ParcelApiAuditParcel} The populated <code>ParcelApiAuditParcel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('changer'))
        obj.changer = ApiClient.convertToType(data['changer'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Date');
      if (data.hasOwnProperty('parcel'))
        obj.parcel = ParcelApiParcel.constructFromObject(data['parcel']);
    }
    return obj;
  }

  /**
   * @member {String} changer
   */
  exports.prototype.changer = undefined;

  /**
   * @member {Date} time
   */
  exports.prototype.time = undefined;

  /**
   * @member {module:model/ParcelApiParcel} parcel
   */
  exports.prototype.parcel = undefined;


  return exports;

}));
