/*
 * service/service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetRolesResponceRole'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GetRolesResponceRole'));
  } else {
    // Browser globals (root is window)
    if (!root.Serviceserviceproto) {
      root.Serviceserviceproto = {};
    }
    root.Serviceserviceproto.AuthApiGetRolesResponce = factory(root.Serviceserviceproto.ApiClient, root.Serviceserviceproto.GetRolesResponceRole);
  }
}(this, function(ApiClient, GetRolesResponceRole) {
  'use strict';

  /**
   * The AuthApiGetRolesResponce model module.
   * @module model/AuthApiGetRolesResponce
   * @version version not set
   */

  /**
   * Constructs a new <code>AuthApiGetRolesResponce</code>.
   * @alias module:model/AuthApiGetRolesResponce
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AuthApiGetRolesResponce</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthApiGetRolesResponce} obj Optional instance to populate.
   * @return {module:model/AuthApiGetRolesResponce} The populated <code>AuthApiGetRolesResponce</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], [GetRolesResponceRole]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/GetRolesResponceRole>} roles
   */
  exports.prototype.roles = undefined;


  return exports;

}));
