/*
 * service/service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.28-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ParcelApiSizes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ParcelApiSizes'));
  } else {
    // Browser globals (root is window)
    if (!root.Serviceserviceproto) {
      root.Serviceserviceproto = {};
    }
    root.Serviceserviceproto.ParcelApiSaveParcelSizeRequest = factory(root.Serviceserviceproto.ApiClient, root.Serviceserviceproto.ParcelApiSizes);
  }
}(this, function(ApiClient, ParcelApiSizes) {
  'use strict';

  /**
   * The ParcelApiSaveParcelSizeRequest model module.
   * @module model/ParcelApiSaveParcelSizeRequest
   * @version version not set
   */

  /**
   * Constructs a new <code>ParcelApiSaveParcelSizeRequest</code>.
   * @alias module:model/ParcelApiSaveParcelSizeRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ParcelApiSaveParcelSizeRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ParcelApiSaveParcelSizeRequest} obj Optional instance to populate.
   * @return {module:model/ParcelApiSaveParcelSizeRequest} The populated <code>ParcelApiSaveParcelSizeRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('parcelId'))
        obj.parcelId = ApiClient.convertToType(data['parcelId'], 'String');
      if (data.hasOwnProperty('sizes'))
        obj.sizes = ParcelApiSizes.constructFromObject(data['sizes']);
    }
    return obj;
  }

  /**
   * @member {String} parcelId
   */
  exports.prototype.parcelId = undefined;

  /**
   * @member {module:model/ParcelApiSizes} sizes
   */
  exports.prototype.sizes = undefined;


  return exports;

}));
